blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.PostList.as_view(), name="post_list"),
    path(
        "post_detail/<slug>/",
        views.PostDetail.as_view(),
        name="post_detail",
    ),
    path("create_post/", views.PostCreateView.as_view(), name="create_post"),
    path("edit_post/<slug>/", views.PostEditView.as_view(), name="edit_post"),
    path(
        "delete_post/<slug>/",
        views.PostDeleteView.as_view(),
        name="delete_post",
    ),
]

oma_k_ron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import handler400, handler403, handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "oma_k_ron.views.handler400"
handler403 = "oma_k_ron.views.handler403"
handler404 = 'oma_k_ron.views.handler404'
handler500 = "oma_k_ron.views.handler500"

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.all_products, name="products"),
    path("<int:product_id>/", views.product_detail, name="product_detail"),
    path("add/", views.add_product, name="add_product"),
    path("edit/<int:product_id>/", views.edit_product, name="edit_product"),
    path(
        "delete/<int:product_id>/",
        views.delete_product,
        name="delete_product",
    ),
]

products/models.py
from django.db import models


class ProductType(models.Model):
    """
    A model to define if the product is a macaron or an event
    """
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Category(models.Model):
    """ A model to define the category of product """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    This class creates a table in the database to storage product
    information.
    """
    class Meta:
        ordering = ["product_type", "date_of_event"]
    name = models.CharField(max_length=250, )
    product_type = models.ForeignKey(
        'ProductType',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        default=1
    )
    category = models.ForeignKey(
        'Category',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    style = models.CharField(max_length=250, blank=True, null=True)
    flavour = models.CharField(max_length=250, blank=True, null=True)
    description = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    duration = models.IntegerField(blank=True, null=True)
    date_of_event = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    """ This class creates a custom form for the Product model """
    class Meta:
        model = Product
        fields = "__all__"
        widgets = {
            "date_of_event": forms.TextInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "border-black"

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from datetime import date

from .models import Product
from .forms import ProductForm


def all_products(request):
    """
    A view to display all products, including sorting and search queries.
    """
    products = Product.objects.filter(
        Q(product_type="1")
        | Q(date_of_event__gt=date.today())
    )
    query = None
    product_type = None
    sort = None
    direction = None

    if request.GET:
        if "sort" in request.GET:
            sortkey = request.GET["sort"]
            sort = sortkey
            if sortkey == "style":
                products = products.filter(product_type=1)
            if sortkey == "name":
                sortkey = "lower_name"
                products = products.annotate(lower_name=Lower("name"))
            if "direction" in request.GET:
                direction = request.GET["direction"]
                if direction == "desc":
                    sortkey = f"-{sortkey}"
            products = products.order_by(sortkey)

        if "product_type" in request.GET:
            product_type = request.GET["product_type"]
            products = products.filter(product_type__name=product_type)
            # if product_type == 2:
            #     products = products.filter(date_of_event__gt=date.today)

        if "category" in request.GET:
            category = request.GET["category"]
            products = products.filter(category__name=category)

        if "q" in request.GET:
            query = request.GET["q"]
            if not query:
                messages.error(
                    request,
                    "You did not enter any search criteria!",
                )
                return redirect(reverse('products'))
            queries = Q(
                name__icontains=query
            ) | Q(
                description__icontains=query
            ) | Q(
                flavour__icontains=query
            )
            products = products.filter(queries)

    current_sorting = f"{sort}_{direction}"

    context = {
        "products": products,
        "search_term": query,
        "current_product_type": product_type,
        "current_sorting": current_sorting,
    }
    return render(request, 'products/all_products.html', context)


def product_detail(request, product_id):
    """
    A view to display details of a specific product.
    """
    product = get_object_or_404(Product, pk=product_id)
    context = {
        "product": product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the store

    This view is restricted to superusers only
    """
    if not request.user.is_superuser:
        messages.error(
            request,
            "Sorry, this page is restricted to the store owners.",
        )
        return redirect(reverse("home"))
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, "Product successfully added!")
            return redirect(reverse("product_detail", args=[product.id]))
        else:
            messages.error(
                request,
                "Failed to add product. Please ensure the form is valid",
            )
    else:
        form = ProductForm()
    template = "products/add_product.html"
    context = {
        "form": form,
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store

    This view is restricted to superusers only
    """
    if not request.user.is_superuser:
        messages.error(
            request,
            "Sorry, this page is restricted to the store owners.",
        )
        return redirect(reverse("home"))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Product successfully updated!")
            return redirect(reverse("product_detail", args=[product.id]))
        else:
            messages.error(
                request,
                "Failed to update product. Please ensure the form is valid.",
            )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f"You are editing {product.name}")
    template = "products/edit_product.html"
    context = {
        "form": form,
        "product": product,
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store

    This view is restricted to superusers only
    """
    if not request.user.is_superuser:
        messages.error(
            request,
            "Sorry, this page is restricted to the store owners.",
        )
        return redirect(reverse("home"))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        product.delete()
        messages.success(request, "Product successfully deleted!")
        return redirect(reverse("products"))
    context = {
        "product": product,
    }
    return render(request, "products/delete_product.html", context)

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Product Management{% endblock extra_title %}

{% block content %}
<div class="forms-background">
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
            <h2 class="logo-font text-center mb-4">Product Management</h2>
            <hr class="w-50 mb-1">
            <H5 class="text-muted text-center">Add a Product</H5>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
            <form action="{% url 'add_product' %}" class="form mb-2 px-3" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black" aria-label="Go back to the list of products">Cancel</a>
                    <button class="btn bg-blue font-weight-bold" type="submit" aria-label="Submit the form to add the product to the database">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script>
        let productType = document.querySelector('#id_product_type');
        document.querySelector("#div_id_duration").style.display = "none";
        document.querySelector("#div_id_date_of_event").style.display = "none";
        productType.addEventListener("change", (event) => {
            if (event.target.value === "1") {
                document.querySelector("#div_id_duration").style.display = "none";
                console.log(document.querySelector("#div_id_duration").style.display);
                document.querySelector("#div_id_date_of_event").style.display = "none";
                document.querySelector("#div_id_style").style.display = "block";
                document.querySelector("#div_id_flavour").style.display = "block";
            } else if (event.target.value === "2") {
                document.querySelector("#div_id_duration").style.display = "block";
                console.log(document.querySelector("#div_id_duration").style.display);
                document.querySelector("#div_id_date_of_event").style.display = "block";
                document.querySelector("#div_id_style").style.display = "none";
                document.querySelector("#div_id_flavour").style.display = "none";
            }
        });
    </script>
{% endblock postload_js %}

products/templates/products/all_products.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Products{% endblock extra_title %}

{% block content %}
    <div class="row">
        <div class="col text-center">
            <h2 class="logo-font">
                {% if 'macaron' in request.get_full_path or 'single' in request.get_full_path or 'box' in request.get_full_path or 'tower' in request.get_full_path %}
                    Our Macarons
                {% elif 'event' in request.get_full_path or 'course' in request.get_full_path or 'visit' in request.get_full_path %}
                    Our Events
                {% else %}
                    All Products
                {% endif %}
            </h2>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="btt-button bg-blue">
        <a class="btt-link d-flex h-100" aria-label="Go back to the top of the current page">
            <i class="fas fa-arrow-up text-black mx-auto my-auto" aria-hidden="true"></i>
        </a>
    </div>
    <div class="row">
        <div class="product-container col-10 offset-1">
            <div class="row mt-1 mb-2">
                <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                    <div class="sort-select-wrapper w-50">
                        <select id="sort-selector"
                            class="custom-select custom-select-sm border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                            <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
                            </option>
                            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)
                            </option>
                            <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                            <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                            <option value="style_asc" {% if current_sorting == 'style_asc' %}selected{% endif %}>Style (A-Z)
                            </option>
                            <option value="style_desc" {% if current_sorting == 'style_desc' %}selected{% endif %}>Style
                                (Z-A)</option>
                        </select>
                    </div>
                </div>
                <div class="col-12 col-md-6 order-md-first">
                    <p class="text-muted mt-3 text-center text-md-left">
                        {% if search_term or current_sorting != 'None_None' %}
                        <span class="small"><a href="{% url 'products' %}" aria-label="Go back to the list of products">All Products</a> | </span>
                        {% endif %}
                        {{ products|length }} Products{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                    </p>
                </div>
            </div>
            <div class="row gap-0">
                {% for product in products %}
                    <div class="col-sm-6 col-lg-4 col-xl-3 p-2">
                        <div class="card m-0">
                            <div class="img-container mx-auto">
                                {% if product.image %}
                                <a href="{% url 'product_detail' product.id %}" aria-label="Go to the details of {{ product.name }}">
                                    <img src="{{ product.image.url }}" alt="{{ product.description }}" class="card-img-top img-fluid">
                                </a>
                                {% else %}
                                <a href="{% url 'product_detail' product.id %}" aria-label="Go to the details of {{ product.name }}">
                                    <img src="{{ MEDIA_URL }}no_image.jpg" alt="{{ product.description }}" class="card-img-top img-fluid">
                                </a>
                                {% endif %}
                            </div>
                            <div class="card-body card-body-product pb-1">
                                {% if request.user.is_superuser %}
                                    <div class="text-center">
                                        <small class="ml-3">
                                            <a href="{% url 'edit_product' product.id %}" aria-label="Go the edit page of {{ product.name }}">Edit</a> |
                                            <a class="text-danger" href="{% url 'delete_product' product.id %}" aria-label="Delete {{ product.name }} from the database">Delete</a>
                                        </small>
                                    </div>
                                {% endif %}
                                <h4 class="mb-0 text-center font-weight-bold">{{ product.name }}</h4>
                                {% if product.style %}
                                    <p class="text-center">{{ product.style | title }} style</p>
                                {% endif %}
                                {% if product.flavour %}
                                <p class="lead m-0 text-left"><small>flavour: {{ product.flavour }}</small></p>
                                {% endif %}
                                {% if product.date_of_event %}
                                <p class="text-center mt-2 mb-0">{{ product.date_of_event | date:"D jS \o\f M\. Y \a\t P" }}</p>
                                {% endif %}
                                {% if product.duration %}
                                <p class="text-center">duration: {{ product.duration }} minutes</p>
                                {% endif %}
                            </div>
                            <div class="card-footer bg-pink py-2 border-0 text-left">
                                <div class="row">
                                    <div class="col">
                                        <p class="lead mb-0 text-right font-weight-bold">{{ product.price }} €</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script>
        $('.btt-link').click(function (e) {
            window.scrollTo({
                top: 0,
                left: 0,
                behavior: "smooth",
            });
        })
    </script>
    <script>
        $('#sort-selector').change(function() {
            var selector = $(this)
            var currentUrl = new URL(window.location);
            var selectedVal = selector.val();
            if(selectedVal != "reset") {
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];
                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);
                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort")
                currentUrl.searchParams.delete("direction")
                window.location.replace(currentUrl);
            }
        }
        )
    </script>
{% endblock postload_js %}

products/templates/products/delete_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Product Management{% endblock extra_title %}

{% block content %}
<div class="row">
    <div class="col-12 col-lg-6 offset-lg-3">
        <h2 class="logo-font text-center mb-4">Product Management</h2>
        <hr class="w-50 mb-1">
        <H5 class="text-muted text-center">Do you really want to delete this item?</H5>
    </div>
</div>
<div class="row">
    <div class="col-12 col-lg-6 offset-lg-3">
        <form action="{% url 'delete_product' product.id %}" class="form mb-2 px-3" method="POST">
            {% csrf_token %}
            <div class="text-right">
                <a href="{% url 'products' %}" class="btn btn-outline-black" aria-label="Go back to the list of products">Cancel</a>
                <button class="btn btn-danger font-weight-bold" type="submit" aria-label="Delete {{ product.name }} from the database">Delete Product</button>
            </div>
        </form>
    </div>
</div>
<div class="row p-4">
    
</div>
{% endblock content %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Product Management{% endblock extra_title %}

{% block content %}
<div class="forms-background">
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
            <h2 class="logo-font text-center mb-4">Product Management</h2>
            <hr class="w-50 mb-1">
            <H5 class="text-muted text-center">Edit Product</H5>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
            <form action="{% url 'edit_product' product.id %}" class="form mb-2 px-3" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black" aria-label="Go back to the list of products">Cancel</a>
                    <button class="btn bg-blue font-weight-bold" type="submit" aria-label="Update the details of {{ product.name }}">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script>
        let productType = document.querySelector('#id_product_type');
        if (productType.value == 1) {
            document.querySelector("#div_id_duration").style.display = "none";
            document.querySelector("#div_id_date_of_event").style.display = "none";
        } else {
            document.querySelector("#div_id_style").style.display = "none";
            document.querySelector("#div_id_flavour").style.display = "none";
        }
        productType.addEventListener("change", (event) => {
            if (event.target.value === "1") {
                document.querySelector("#div_id_duration").style.display = "none";
                console.log(document.querySelector("#div_id_duration").style.display);
                document.querySelector("#div_id_date_of_event").style.display = "none";
                document.querySelector("#div_id_style").style.display = "block";
                document.querySelector("#div_id_flavour").style.display = "block";
            } else if (event.target.value === "2") {
                document.querySelector("#div_id_duration").style.display = "block";
                console.log(document.querySelector("#div_id_duration").style.display);
                document.querySelector("#div_id_date_of_event").style.display = "block";
                document.querySelector("#div_id_style").style.display = "none";
                document.querySelector("#div_id_flavour").style.display = "none";
            }
        });
    </script>
{% endblock postload_js %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Product Detail{% endblock extra_title %}

{% block content %}
<div class="row">
    <div class="col-12 col-md-6 col-lg-4 offset-lg-2 px-2">
        <div class="image-container my-5">
            {% if product.image %}
            <a href="{{ product.image.url }}" aria-label="Open the image of {{ product.name }} in a new tab" target="_blank">
                <img src="{{ product.image.url }}" alt="{{ product.description }}" class="img-fluid">
            </a>
            {% else %}
            <a href="">
                <img src="{{ MEDIA_URL }}no_image.jpg" alt="{{ product.description }}" class="card-img-top img-fluid">
            </a>
            {% endif %}
        </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4 px-2">
        <div class="product-details-container mb-5 mt-md-5">
            <h4 class="mb-0 text-center font-weight-bold">{{ product.name }}</h4>
            {% if request.user.is_superuser %}
            <div class="text-center">
                <small>
                    <a href="{% url 'edit_product' product.id %}" aria-label="Go to the modification page of {{ product.name }}">Edit</a> |
                    <a class="text-danger" href="{% url 'delete_product' product.id %}" aria-label="Delete {{ product.name }} from the database">Delete</a>
                </small>
            </div>
            {% endif %}
            <p class="mt-3 text-center">{{ product.description }}</p>
            {% if product.style %}
            <p class="text-center mt-3">style: {{ product.style }}</p>
            {% endif %}
            {% if product.flavour %}
                <p class="text-center mt-3">flavour: {{ product.flavour }}</p>
            {% endif %}
            {% if product.date_of_event %}
                <p class="text-center mt-3"><strong>{{ product.date_of_event | date:"D jS \o\f M\. Y \a\t P" }}</strong></p>
            {% endif %}
            {% if product.duration %}
                <p class="text-center mt-3">duration: {{ product.duration }} minutes</p>
            {% endif %}
            <p class="lead mb-0 text-center font-weight-bold">{{ product.price }} €</p>
            <form action="{% url 'add_to_cart' product.id %}" class="form" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-12">
                        <p class="mt-3"><strong>Quantity:</strong></p>
                        <div class="form-group w-md-50">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn btn-black" data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}" aria-label="Decrement the quantity of {{ product.name }}">
                                        <span class="icon">
                                            <i class="fas fa-minus" aria-hidden="true"></i>
                                        </span>
                                    </button>
                                </div>
                                <input type="number" class="form-control qty_input text-center" name="quantity" value="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                <div class="input-group-append">
                                    <button class="increment-qty btn btn-black" data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}" aria-label="Increment the quantity of {{ product.name }}">
                                        <span class="icon">
                                            <i class="fas fa-plus" aria-hidden="true"></i>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <a href="{% url 'products' %} " class="btn btn-outline-black mt-5" aria-label="Go back to the list of products">
                            <span class="icon">
                                <i class="fas fa-chevron-left" aria-hidden="true"></i>
                            </span>
                            <span class="text-uppercase">Keep Shopping</span>
                        </a>
                        <input type="submit" class="btn bg-blue font-weight-bold mt-5" value="Add to Cart">
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    {% include 'products/includes/quantity_input_script.html' %}
{% endblock postload_js %}